
package Vista;

public class Menu extends javax.swing.JFrame {

    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btt_Grupo_Jug = new javax.swing.ButtonGroup();
        PanelFondo1 = new javax.swing.JPanel();
        PanelPestanias = new javax.swing.JTabbedPane();
        Pestania_Jugadoras = new javax.swing.JPanel();
        Lbl_Jug_Menu = new javax.swing.JLabel();
        Btt_Cargar_Jug = new javax.swing.JRadioButton();
        Btt_Eliminar_Jug = new javax.swing.JRadioButton();
        Btt_BuscarCod_Jug = new javax.swing.JRadioButton();
        Btt_Actualizar_Jug = new javax.swing.JRadioButton();
        Btt_CantEquipo_Jug = new javax.swing.JRadioButton();
        Btt_Posicion_Jug = new javax.swing.JRadioButton();
        Btt_Goles_Jug = new javax.swing.JRadioButton();
        Btt_BuscarNom_Jug = new javax.swing.JRadioButton();
        Btt_MostrarEqui_Jug = new javax.swing.JRadioButton();
        Btt_TRojas_Jug = new javax.swing.JRadioButton();
        Pestanias_Menu_Jugadoras = new javax.swing.JTabbedPane();
        Panel_Cargar = new javax.swing.JPanel();
        Panel_Eliminar = new javax.swing.JPanel();
        Panel_Actualizar = new javax.swing.JPanel();
        Panel_BusCodigo = new javax.swing.JPanel();
        Panel_BusNombre = new javax.swing.JPanel();
        Panel_Goles = new javax.swing.JPanel();
        Panel_Posicion = new javax.swing.JPanel();
        Panel_CantEquipo = new javax.swing.JPanel();
        Panel_TRojas = new javax.swing.JPanel();
        Panel_Mostrar = new javax.swing.JPanel();
        Pestania_Arbitros = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 510));

        PanelFondo1.setBackground(new java.awt.Color(204, 204, 255));

        PanelPestanias.setBackground(new java.awt.Color(255, 255, 153));

        Pestania_Jugadoras.setBackground(new java.awt.Color(255, 228, 244));

        Lbl_Jug_Menu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Lbl_Jug_Menu.setText("Menu:");

        Btt_Grupo_Jug.add(Btt_Cargar_Jug);
        Btt_Cargar_Jug.setText("Cargar ");
        Btt_Cargar_Jug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btt_Cargar_JugMouseClicked(evt);
            }
        });

        Btt_Grupo_Jug.add(Btt_Eliminar_Jug);
        Btt_Eliminar_Jug.setText("Eliminar");
        Btt_Eliminar_Jug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btt_Eliminar_JugMouseClicked(evt);
            }
        });

        Btt_Grupo_Jug.add(Btt_BuscarCod_Jug);
        Btt_BuscarCod_Jug.setText("Buscar por Codigo");
        Btt_BuscarCod_Jug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btt_BuscarCod_JugMouseClicked(evt);
            }
        });

        Btt_Grupo_Jug.add(Btt_Actualizar_Jug);
        Btt_Actualizar_Jug.setText("Actualizar Datos");
        Btt_Actualizar_Jug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btt_Actualizar_JugMouseClicked(evt);
            }
        });

        Btt_Grupo_Jug.add(Btt_CantEquipo_Jug);
        Btt_CantEquipo_Jug.setText("Cant por Equipo");
        Btt_CantEquipo_Jug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btt_CantEquipo_JugMouseClicked(evt);
            }
        });
        Btt_CantEquipo_Jug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_CantEquipo_JugActionPerformed(evt);
            }
        });

        Btt_Grupo_Jug.add(Btt_Posicion_Jug);
        Btt_Posicion_Jug.setText("Por posicion");
        Btt_Posicion_Jug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btt_Posicion_JugMouseClicked(evt);
            }
        });

        Btt_Grupo_Jug.add(Btt_Goles_Jug);
        Btt_Goles_Jug.setText("Mas goles");
        Btt_Goles_Jug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btt_Goles_JugMouseClicked(evt);
            }
        });

        Btt_Grupo_Jug.add(Btt_BuscarNom_Jug);
        Btt_BuscarNom_Jug.setText("Buscar por Nombre");
        Btt_BuscarNom_Jug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btt_BuscarNom_JugMouseClicked(evt);
            }
        });

        Btt_Grupo_Jug.add(Btt_MostrarEqui_Jug);
        Btt_MostrarEqui_Jug.setText("Mostrar Equipo");
        Btt_MostrarEqui_Jug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btt_MostrarEqui_JugMouseClicked(evt);
            }
        });

        Btt_Grupo_Jug.add(Btt_TRojas_Jug);
        Btt_TRojas_Jug.setText("Tarjetas rojas");
        Btt_TRojas_Jug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btt_TRojas_JugMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_CargarLayout = new javax.swing.GroupLayout(Panel_Cargar);
        Panel_Cargar.setLayout(Panel_CargarLayout);
        Panel_CargarLayout.setHorizontalGroup(
            Panel_CargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        Panel_CargarLayout.setVerticalGroup(
            Panel_CargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        Pestanias_Menu_Jugadoras.addTab("tab1", Panel_Cargar);

        javax.swing.GroupLayout Panel_EliminarLayout = new javax.swing.GroupLayout(Panel_Eliminar);
        Panel_Eliminar.setLayout(Panel_EliminarLayout);
        Panel_EliminarLayout.setHorizontalGroup(
            Panel_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        Panel_EliminarLayout.setVerticalGroup(
            Panel_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        Pestanias_Menu_Jugadoras.addTab("tab2", Panel_Eliminar);

        javax.swing.GroupLayout Panel_ActualizarLayout = new javax.swing.GroupLayout(Panel_Actualizar);
        Panel_Actualizar.setLayout(Panel_ActualizarLayout);
        Panel_ActualizarLayout.setHorizontalGroup(
            Panel_ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        Panel_ActualizarLayout.setVerticalGroup(
            Panel_ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        Pestanias_Menu_Jugadoras.addTab("tab3", Panel_Actualizar);

        javax.swing.GroupLayout Panel_BusCodigoLayout = new javax.swing.GroupLayout(Panel_BusCodigo);
        Panel_BusCodigo.setLayout(Panel_BusCodigoLayout);
        Panel_BusCodigoLayout.setHorizontalGroup(
            Panel_BusCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        Panel_BusCodigoLayout.setVerticalGroup(
            Panel_BusCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        Pestanias_Menu_Jugadoras.addTab("tab4", Panel_BusCodigo);

        javax.swing.GroupLayout Panel_BusNombreLayout = new javax.swing.GroupLayout(Panel_BusNombre);
        Panel_BusNombre.setLayout(Panel_BusNombreLayout);
        Panel_BusNombreLayout.setHorizontalGroup(
            Panel_BusNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        Panel_BusNombreLayout.setVerticalGroup(
            Panel_BusNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        Pestanias_Menu_Jugadoras.addTab("tab5", Panel_BusNombre);

        javax.swing.GroupLayout Panel_GolesLayout = new javax.swing.GroupLayout(Panel_Goles);
        Panel_Goles.setLayout(Panel_GolesLayout);
        Panel_GolesLayout.setHorizontalGroup(
            Panel_GolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        Panel_GolesLayout.setVerticalGroup(
            Panel_GolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        Pestanias_Menu_Jugadoras.addTab("tab6", Panel_Goles);

        javax.swing.GroupLayout Panel_PosicionLayout = new javax.swing.GroupLayout(Panel_Posicion);
        Panel_Posicion.setLayout(Panel_PosicionLayout);
        Panel_PosicionLayout.setHorizontalGroup(
            Panel_PosicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        Panel_PosicionLayout.setVerticalGroup(
            Panel_PosicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        Pestanias_Menu_Jugadoras.addTab("tab7", Panel_Posicion);

        javax.swing.GroupLayout Panel_CantEquipoLayout = new javax.swing.GroupLayout(Panel_CantEquipo);
        Panel_CantEquipo.setLayout(Panel_CantEquipoLayout);
        Panel_CantEquipoLayout.setHorizontalGroup(
            Panel_CantEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        Panel_CantEquipoLayout.setVerticalGroup(
            Panel_CantEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        Pestanias_Menu_Jugadoras.addTab("tab8", Panel_CantEquipo);

        javax.swing.GroupLayout Panel_TRojasLayout = new javax.swing.GroupLayout(Panel_TRojas);
        Panel_TRojas.setLayout(Panel_TRojasLayout);
        Panel_TRojasLayout.setHorizontalGroup(
            Panel_TRojasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        Panel_TRojasLayout.setVerticalGroup(
            Panel_TRojasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        Pestanias_Menu_Jugadoras.addTab("tab9", Panel_TRojas);

        javax.swing.GroupLayout Panel_MostrarLayout = new javax.swing.GroupLayout(Panel_Mostrar);
        Panel_Mostrar.setLayout(Panel_MostrarLayout);
        Panel_MostrarLayout.setHorizontalGroup(
            Panel_MostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        Panel_MostrarLayout.setVerticalGroup(
            Panel_MostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        Pestanias_Menu_Jugadoras.addTab("tab10", Panel_Mostrar);

        javax.swing.GroupLayout Pestania_JugadorasLayout = new javax.swing.GroupLayout(Pestania_Jugadoras);
        Pestania_Jugadoras.setLayout(Pestania_JugadorasLayout);
        Pestania_JugadorasLayout.setHorizontalGroup(
            Pestania_JugadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pestania_JugadorasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(Pestania_JugadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btt_TRojas_Jug)
                    .addComponent(Btt_CantEquipo_Jug)
                    .addComponent(Btt_Posicion_Jug)
                    .addComponent(Btt_Goles_Jug)
                    .addComponent(Btt_BuscarNom_Jug)
                    .addComponent(Btt_BuscarCod_Jug)
                    .addComponent(Btt_Actualizar_Jug)
                    .addComponent(Btt_Eliminar_Jug)
                    .addComponent(Btt_Cargar_Jug)
                    .addComponent(Lbl_Jug_Menu)
                    .addComponent(Btt_MostrarEqui_Jug))
                .addGap(18, 18, 18)
                .addComponent(Pestanias_Menu_Jugadoras, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Pestania_JugadorasLayout.setVerticalGroup(
            Pestania_JugadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pestania_JugadorasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Lbl_Jug_Menu)
                .addGap(18, 18, 18)
                .addComponent(Btt_Cargar_Jug)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btt_Eliminar_Jug)
                .addGap(8, 8, 8)
                .addComponent(Btt_Actualizar_Jug)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btt_BuscarCod_Jug)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btt_BuscarNom_Jug)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btt_Goles_Jug)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btt_Posicion_Jug)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btt_CantEquipo_Jug)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btt_TRojas_Jug)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btt_MostrarEqui_Jug)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Pestania_JugadorasLayout.createSequentialGroup()
                .addComponent(Pestanias_Menu_Jugadoras, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        PanelPestanias.addTab("Jugadoras", Pestania_Jugadoras);

        Pestania_Arbitros.setBackground(new java.awt.Color(222, 249, 211));

        javax.swing.GroupLayout Pestania_ArbitrosLayout = new javax.swing.GroupLayout(Pestania_Arbitros);
        Pestania_Arbitros.setLayout(Pestania_ArbitrosLayout);
        Pestania_ArbitrosLayout.setHorizontalGroup(
            Pestania_ArbitrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        Pestania_ArbitrosLayout.setVerticalGroup(
            Pestania_ArbitrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        PanelPestanias.addTab("Arbitros", Pestania_Arbitros);

        javax.swing.GroupLayout PanelFondo1Layout = new javax.swing.GroupLayout(PanelFondo1);
        PanelFondo1.setLayout(PanelFondo1Layout);
        PanelFondo1Layout.setHorizontalGroup(
            PanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPestanias)
        );
        PanelFondo1Layout.setVerticalGroup(
            PanelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPestanias)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btt_CantEquipo_JugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_CantEquipo_JugActionPerformed
        Pestanias_Menu_Jugadoras.setSelectedIndex(7);
    }//GEN-LAST:event_Btt_CantEquipo_JugActionPerformed

    private void Btt_Cargar_JugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_Cargar_JugMouseClicked
        Pestanias_Menu_Jugadoras.setSelectedIndex(0);
    }//GEN-LAST:event_Btt_Cargar_JugMouseClicked

    private void Btt_Eliminar_JugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_Eliminar_JugMouseClicked
        Pestanias_Menu_Jugadoras.setSelectedIndex(1);
    }//GEN-LAST:event_Btt_Eliminar_JugMouseClicked

    private void Btt_Actualizar_JugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_Actualizar_JugMouseClicked
        Pestanias_Menu_Jugadoras.setSelectedIndex(2);
    }//GEN-LAST:event_Btt_Actualizar_JugMouseClicked

    private void Btt_BuscarCod_JugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_BuscarCod_JugMouseClicked
        Pestanias_Menu_Jugadoras.setSelectedIndex(3);
    }//GEN-LAST:event_Btt_BuscarCod_JugMouseClicked

    private void Btt_BuscarNom_JugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_BuscarNom_JugMouseClicked
        Pestanias_Menu_Jugadoras.setSelectedIndex(4);
    }//GEN-LAST:event_Btt_BuscarNom_JugMouseClicked

    private void Btt_Goles_JugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_Goles_JugMouseClicked
        Pestanias_Menu_Jugadoras.setSelectedIndex(5);
    }//GEN-LAST:event_Btt_Goles_JugMouseClicked

    private void Btt_Posicion_JugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_Posicion_JugMouseClicked
        Pestanias_Menu_Jugadoras.setSelectedIndex(6);
    }//GEN-LAST:event_Btt_Posicion_JugMouseClicked

    private void Btt_CantEquipo_JugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_CantEquipo_JugMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btt_CantEquipo_JugMouseClicked

    private void Btt_TRojas_JugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_TRojas_JugMouseClicked
        Pestanias_Menu_Jugadoras.setSelectedIndex(8);
    }//GEN-LAST:event_Btt_TRojas_JugMouseClicked

    private void Btt_MostrarEqui_JugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_MostrarEqui_JugMouseClicked
        Pestanias_Menu_Jugadoras.setSelectedIndex(9);
    }//GEN-LAST:event_Btt_MostrarEqui_JugMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Btt_Actualizar_Jug;
    private javax.swing.JRadioButton Btt_BuscarCod_Jug;
    private javax.swing.JRadioButton Btt_BuscarNom_Jug;
    private javax.swing.JRadioButton Btt_CantEquipo_Jug;
    private javax.swing.JRadioButton Btt_Cargar_Jug;
    private javax.swing.JRadioButton Btt_Eliminar_Jug;
    private javax.swing.JRadioButton Btt_Goles_Jug;
    private javax.swing.ButtonGroup Btt_Grupo_Jug;
    private javax.swing.JRadioButton Btt_MostrarEqui_Jug;
    private javax.swing.JRadioButton Btt_Posicion_Jug;
    private javax.swing.JRadioButton Btt_TRojas_Jug;
    private javax.swing.JLabel Lbl_Jug_Menu;
    private javax.swing.JPanel PanelFondo1;
    private javax.swing.JTabbedPane PanelPestanias;
    private javax.swing.JPanel Panel_Actualizar;
    private javax.swing.JPanel Panel_BusCodigo;
    private javax.swing.JPanel Panel_BusNombre;
    private javax.swing.JPanel Panel_CantEquipo;
    private javax.swing.JPanel Panel_Cargar;
    private javax.swing.JPanel Panel_Eliminar;
    private javax.swing.JPanel Panel_Goles;
    private javax.swing.JPanel Panel_Mostrar;
    private javax.swing.JPanel Panel_Posicion;
    private javax.swing.JPanel Panel_TRojas;
    private javax.swing.JPanel Pestania_Arbitros;
    private javax.swing.JPanel Pestania_Jugadoras;
    private javax.swing.JTabbedPane Pestanias_Menu_Jugadoras;
    // End of variables declaration//GEN-END:variables
}
