
package Vista;

public class VentanaPrincipal extends javax.swing.JFrame {

    public VentanaPrincipal() {
        initComponents();
        this.setTitle("Asociacion de Futbol");
        this.setSize(1000, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_Asociacion = new javax.swing.JLabel();
        Lbl_Futbol5 = new javax.swing.JLabel();
        Btt_Continuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_Asociacion.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        Lbl_Asociacion.setText("Asociacion");
        getContentPane().add(Lbl_Asociacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        Lbl_Futbol5.setFont(new java.awt.Font("Segoe UI Historic", 0, 36)); // NOI18N
        Lbl_Futbol5.setText("Futbol 5");
        getContentPane().add(Lbl_Futbol5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        Btt_Continuar.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        Btt_Continuar.setText("Continuar");
        Btt_Continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_ContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(Btt_Continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btt_ContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_ContinuarActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_Btt_ContinuarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btt_Continuar;
    private javax.swing.JLabel Lbl_Asociacion;
    private javax.swing.JLabel Lbl_Futbol5;
    // End of variables declaration//GEN-END:variables
}
