
package Vista;

public class VentanaPrincipal extends javax.swing.JFrame {

    public VentanaPrincipal() {
        initComponents();
        this.setTitle("Asociacion de Futbol");
        this.setSize(1100, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_Asociacion = new javax.swing.JLabel();
        Lbl_Futbol5 = new javax.swing.JLabel();
        bttJugadoras = new javax.swing.JButton();
        bttArbitros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_Asociacion.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        Lbl_Asociacion.setText("Asociacion");
        getContentPane().add(Lbl_Asociacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        Lbl_Futbol5.setFont(new java.awt.Font("Segoe UI Historic", 0, 36)); // NOI18N
        Lbl_Futbol5.setText("Futbol 5");
        getContentPane().add(Lbl_Futbol5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        bttJugadoras.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        bttJugadoras.setText("Jugadoras");
        bttJugadoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttJugadorasActionPerformed(evt);
            }
        });
        getContentPane().add(bttJugadoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        bttArbitros.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        bttArbitros.setText("Arbitros");
        bttArbitros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttArbitrosActionPerformed(evt);
            }
        });
        getContentPane().add(bttArbitros, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttJugadorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttJugadorasActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_bttJugadorasActionPerformed

    private void bttArbitrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttArbitrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttArbitrosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_Asociacion;
    private javax.swing.JLabel Lbl_Futbol5;
    private javax.swing.JButton bttArbitros;
    private javax.swing.JButton bttJugadoras;
    // End of variables declaration//GEN-END:variables
}
